title: Byte me
description: A comprehensive documentation of our project
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
nav_links:
  - name: Home
    url: /
  - name: Vision
    url: /vision
  - name: Features
    url: /features
  - name: Contributors
    url: /contributors
  - name: Postmortem
    url: /postmortem